// example17.qasm;
// Compiled with g2q - v1.2.9;
OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c[5];
// Begin g1y;
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
// End g1y;
// Begin ghzy;
// Begin ghzy ladder ascending;
// Begin g1y;
h q[0];
h q[1];
h q[2];
h q[3];
// End g1y;
x q[4];
cx q[3],q[4];
cx q[2],q[4];
cx q[1],q[4];
cx q[0],q[4];
// End ghzy ladder;
// Begin g1y;
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
// End g1y;
// Begin g1y;
barrier q[0];
barrier q[1];
barrier q[2];
barrier q[3];
barrier q[4];
// End g1y;
// End ghzy;
// Begin qmeasy;
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
// End qmeasy;
// qdeclare qx-simulator error_model depolarizing_channel,0.001;
// qdeclare qlib-simulator // Hello qlib-simulator;
